# Site settings
title: About PK
authors: Partheeban Kandasamy
show_downloads: false
description: PK is an expert generalist, loves working with tech and people! 
logo: pk-logo.png
banner_main: assets/images/about/profile.jpg
banner_alt: assets/images/about/ironman.jpeg
people: true
people_limit: 12
twitter: pkblah
email: partheeban.kandasamy@gmail.com
repository: pksrc/about
gh_repo: https://github.com/pksrc/about

google_analytics: UA-141689937-1

hero:
  background-color: cornflower-blue
footer:
  title: Contact PK now! 
  content: Reach out to PK for collaboration , new opportunities and design questions
  cta_title: ''
  cta_url: /kb/
  cta_text: Documentation
  gh-link: http://github.com/pksrc

social_links:
  GitHub:
    fa_icon: fab fa-github
    url: https://github.com/pksrc
  Twitter:
    fa_icon: fab fa-twitter
    url: https://twitter.com/pkblah
  Email:
    fa_icon: fas fa-envelope
    url: mailto:partheeban.kandasamy@gmail.com
    
collections:
  - functions
  - usecases

versioning: false
#latest: v0.3.0
#versions:
#- master
#- v0.3.0
#- v0.2.0

# Build settings
permalink: /blog/:title/
sass:
  sass_dir: assets/css
  style: :compressed

# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

cdn:
  jquery:           "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash:      "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  popper_hash:      "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"

# Use the following plug-ins
plugins:
  - jekyll-readme-index # use README.md as index.html
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-relative-links # Used to auto generate md links to html links
  - jekyll-optional-front-matter # Parse Markdown files that do not have front-matter callouts
  - jekyll-titles-from-headings # pull the page title from the first Markdown heading when none is specified.
  - jekyll-paginate # pagination object for collections (e.g. posts)
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-toc

# Include these subdirectories
include:
  - README.md

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README-JEKYLL.md
  - LICENSE
  - CNAME
  - '*.sh'
