summary: With over 10 years of IT experience working in different roles, I’ve come to realize that I’m passionate towards working closely with technology, addressing customer challenges and business needs with great tools and products.

achievements: 
- Launched an automation tool for VMware Consultants which increases customer engagement time by freeing up 5 hours per resource per week from status reporting
- Launched a BI tool for VMware Product Managers and Marketing to understand customer adoption and analyze trends across industries and market segments
- Designed and Launched a set of tools that help Consultants engage and assess customer readiness on various aspects of technology proficiency, process maturity and team synergy
- MVP, Global Support and Services for exceptional customer service and for contributions towards building labs, training programs and leading the SME team
- Awarded the Outstanding Student Employee of the year, 2013 at UFL for designing and building an inventory management tool
- Co-Inventor & Developer of the patented “Data Audit module for application software” (US9189356 B2)
- Recognized for Academic excellence by Beta Gamma Sigma (Business honor society) and Alpha Iota Delta (Information Systems)

jobs:
 - title: Product Manager, VMware Event Broker Appliance - [vmweventbroker.io](https://bit.ly/vebapm)
   img: vm-logo.png
   duration: Jan 2020 – Present
   description: Managed an early stage, enterprise platform that delivers a Functions as a Service capability (based on OSS technologies such as Kubernetes, Containers) which enable VI Administrators to build efficient automation based on events within SDDC
   stars: 
   - Conducted market research, identifying target customers and refining our user persona (developers and sys admins) 
   - Created [presentations](https://bit.ly/vebapitch), [demos](https://bit.ly/vebavideos) and [evangelize features](https://bit.ly/vebafx) to train internal Stakeholders  and Customers
   - Designed and built our [website](https://bit.ly/vebasiteorigins) from the ground up to improve user engagement, conversion rate and provide enablement
  
 - title: Product Manager - Work Insights, *UW Product Management Certification*
   duration: Mar 2019 – Dec 2019
   description: Conceptualized and Managed an Enterprise HRIS Product for Managers and HR to visualize employee sentiment and improve company culture through actionable and insightful data driven recommendations based on employee engagement, retention & enablement data
   stars: 
   - Market Dynamics - Conducted market analysis through interviews, surveys to understand current challenges with HR industry
   - User Centered Design - Developed prototypes that resonate with target Customer; incorporated feedback into the MVP design
   - Go to Market – Developed marketing strategy and business plan to take Product to Market 

 - title: Customer Success Manager - Workspace One, VMware
   img: vm-logo.png
   duration: Jan 2019 – Present
   description: Customer first, solution focused role dealing with large enterprise Customers to create technical strategy, drive growth and align Product roadmap with Customers’ strategic goals for End User Computing 
   stars: 
   - Drive Product adoption, Business development and Company revenue growth by identifying opportunities, developing Success plans and leading Customer workstreams to improve Employee Experience
   - Translated complex Customer requirements to user stories in JIRA and engaged development team to explain client use-cases, understand technical difficulties, develop acceptance criteria and continuously improve software features 
   - Influenced Product Roadmap prioritization backed with available data, insight into Customer utilization and requirements

 - title: Technical Program Management w/ TAM, VMware 
   img: vm-logo.png
   duration: Jun 2016 - Jun 2019
   description: Conceptualize and launch multiple internal Programs and Products along with process optimizations that helped enable 10x growth of the TAM org globally and drive efficiencies with Customer engagement
   stars: 
   - <b>Status Report Automation</b> – Automated reporting helps TAMs increase Customer engagement time by 12.5% per week 
   - <b>Customer Readiness Assessment</b> – helps TAMs assess Customer technology proficiency, process maturity and team synergy 
   - <b>Utilization dashboard</b> – helps Product and Marketing understand platform utilization and analyze trends across industries
   - <b>Others</b> – Slack My SME for knowledge sharing, Training Bootcamp for quick onboarding, Static Labs for use case validation

 - title: Product Specialist, Technical Account Management, VMware - Jan 2014 – Jun 2018
   img: vm-logo.png
   duration: June 2018 – Present
   awards: Global Support and Services MVP 2015
   description: Fostered lasting Customer relationships to ensure multi-year renewals and net positive spend YoY on Product and Services
   stars: 
   - Served as SME with strong knowledge for Product technology such as Mobility, Application Management, Identity, Networking with strong understanding of open standards such as RESTful APIs, SAML, OAUTH2 and OpenID Connect
   - Customer Advocate collaborating with Product, Engineering, Operations, Sales and Marketing to gather various perspectives, data and insights to drive consensus and formulate action plans for solving Customer issues
   - Helped Customers achieve 300% efficiency with Application deployment cycles by cutting down manual handoff procedures through automation using Rest APIs, Webhooks and SDKs by working hand in hand with development teams

 - title: Software Development Lead, Infinite Energy, Inc. - May 2013 – Dec 2013
   img: IE-logo.png
   duration: June 2018 – Present
   description: Supervised and worked as a team member to build an intranet portal for the Infinite Energy employees using SharePoint
   stars:
   - Scrum Master responsible for daily scrum meetings to ensure that the team is tracking on-time delivery of the product
   - Translate customer requirements to user stories in JIRA and engage development team to explain client use-cases, understand technical difficulties, develop acceptance criteria and continuously improve software features
   - Reviewed team members’ performance to identify areas for improvement and provide constructive feedback

 - title: Student Assistant, University of Florida - J. Wayne Reitz Union - May 2012 - April 2013
   img: uf-logo.svg
   duration: June 2018 – Present
   awards: Awards – Outstanding Student Employee of the year, 2013
   description: Gathered business requirements, designed and developed database solutions using MS Access and MSSQL
   stars: 
   - Worked with the Director of Operations to conceptualize and built a new inventory tracking system for the Operations Department of Reitz Union

 - title: Senior Software Developer, Tata Consultancy Services Ltd. - Nov 2008 - Dec 2011
   img: tcs-logo.svg
   duration: June 2018 – Present
   awards: Certifications – Sun Certified Java Programmer
   description: Worked on multiple projects that used Client/Server architecture performing requirement gathering, design, development, unit testing, implementation and maintenance
   stars:
   - Focused on re-engineering and re-designing Kiosk and Web Check-In applications for Hawaiian Airlines
   - Implemented Agile Scrum Methodology and functioned as the Scrum Master for an eight-member team
   - Performed a Technical Lead role in the Architecture Board working on installations and configuration of Quality Management Tools (Hudson, Sonar) to upkeep the process and quality adherence for various Projects
   - Developed secure web portal that enabled the Orissa state government transition from paper records to electronic records
   - Built a customizable array based workflow engine to accommodate any workflow changes without any development efforts
   - Co-Inventor & Developer of the patented “Data Audit module for application software” (US9189356 B2)

certifications: 
 - University of Washington - Software Product Management 2019 (In Progress)
 - Grow with Google Challenge Scholarship – Android Developer
 - VCP - DW 2019, VMware vSphere Foundations
 - Certified in ITIL Foundations V3– 2016

education: 
 - what: Certified Product Manager, University of Washington
   when: Dec 2019
 - what: Certified Scrum Master, Scrum Alliance
   when: Jun 2019
 - what: Masters in Information Systems & Operations Management, University of Florida
   when: Dec 2013 #Recognized for Academic Excellence by Beta Gamma Sigma and Alpha Iota Delta
 - what: Bachelors in Electronics and Communication Engineering, Madras Institute of Technology
   when: May 2008
